title: Life in tech and medicine
author: Dike Merit
theme: minima
email: your-email@domain.com
description: talking about how i am able to navigate through tech and medicine as i have found passion in both

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
